---
title: "Задание"
---

Для оценки за мастер-классы вам нужно будет выполнить задание по подготовке карты в QGIS.

У вас есть два варианта выполнения задания:

1.  сделать карту на основе исторической;

2.  сделать карту по современным данным.

Ниже описан **примерный порядок** действий для каждого из вариантов.

В любом из вариантов выполнения задания на первом этапе вам нужно определиться с тем, что вы хотите показать на карте и какие данные вам для этого нужны.

::: callout-important
Срок сдачи работы до 24 июня включительно.

Работу можно отправить по ссылке
:::

# Вариант 1

Если вы выберете создание карты на основе исторической, то ваш порядок выполнения задания может быть следующим:

-   выбрать оригинал исторической карты, загрузить его;

-   создать новый проект;

-   сделать его геопривязку;

-   добавить на карту векторные данные (можете выбрать, что вам более интересно)

    -   современные векторные данные из дополнительных источников;

    -   векторизованные исторические данные на основе вашей привязанной карты

-   задать стили своим векторным слоям;

-   оформить карту на листе;

-   добавить необходимые элементы - обязательными элементами масштабная линейка и легенда, все остальные элементы на ваше усмотрение;

-   экспортировать карту из макета в формат pdf или png и отправить ее

# Вариант 2

Если вы будете делать карту только на основе современных данных, то ваш примерный порядок действий может быть таким:

-   выбрать территорию (она может быть абсолютно любой на ваш выбор - ваш любимый район или город, район вашего исследования);

-   создать новый проект;

-   скачать и добавить подложку и данные в ваш проект (это могут быть любые скачанные вами данные из открытых источников или созданные вами самостоятельно);

-   задать стили вашим слоям (тут все ограничивается только вашей фантазией и художественными предпочтениями - это может быть просто выбранный вами стиль заливки или стиль, заданный на основе какого-то параметра, художественный стиль);

-   оформить карту на макете - обязательными элементами макета являются название, масштабная линейка и легенда, все остальные элементы на ваше усмотрение;

-   экспортировать карту из макета в формат pdf или png и отправить ее в форму по ссылке.

# Критерии оценивания

## Содержание

-   2 балла - у карты есть понятная тема, которая хорошо проиллюстрирована;

-   1 балл - тема карты не ясна;

-   0 баллов - тема отсутствует.

## Визуализация

-   4 балла - все знаки и символы хорошо различимы и читаемы, выбрана подходящая цветовая палитра и верный способ отображения данных;

-   2-3 балла - слабая контрастность символов, неправильно подобранная цветовая палитра;

-   1 балл - карта плохо читаема, выбран неверно выбранный способ отображения;

-   0 баллов - отсутствует наглядная визуализация.

## Оформление

-   4 балла - все необходимые элементы оформления присутствуют: есть название, масштабная линейка и легенда; легенда читаемая и не имеет неясных надписей;

-   2-3 балла - отсутствует какой-либо из элементов либо один из элементов оформлен неправильно;

-   1 балл - отсутствует более одного элемента оформления, все элементы оформлены неправильно;

-   0 баллов - нет элементов оформления.
