---
title: "Домашнее задание"
---

::: callout-important
Домашнее задание является вашей контрольной точкой, поэтому его выполнение обязательно!
:::

Вам нужно подготовить и оформить карту любой территории на свой выбор.

Порядок работы:

1.  выбрать территорию (она может быть абсолютно любой на ваш выбор - ваш любимый район или город, район вашего исследования);

2.  создать новый проект;

3.  скачать и добавить подложку и данные в ваш проект (это могут быть любые скачанные вами данные из открытых источников или созданные вами самостоятельно);

4.  задать стили вашим слоям (тут все ограничивается только вашей фантазией и художественными предпочтениями - это может быть просто выбранный вами стиль заливки или стиль, заданный на основе какого-то параметра, художественный стиль);

5.  оформить карту на макете - обязательными элементами макета являются карта, масштабная линейка и легенда, все остальные элементы на ваше усмотрение;

6.  экспортировать карту из макета в формат pdf или png и отправить ее в форму по ссылке.

Задание можно загрузить по ссылке <https://forms.yandex.ru/u/671a67d05d2a0698658995b2>

**Срок сдачи работы: до *23 ноября включительно***
