---
title: "О курсе"
date: today
date-format: "D MMMM YYYY"
number-sections: false
author:
  - name: Балтыжакова Татьяна
abstract: Материалы мастер-классов для магистерской программы НИУ ВШЭ ‘Цифровые методы в гуманитарных науках’ (2025/2026)
---

## Преподаватель {.unnumbered}

[Балтыжакова Татьяна Игоревна](https://edu.itmo.ru/ru/lecturers_and_professors/329024), кандидат технических наук, доцент Института дизайна и урбанистики.

# Общие сведения

Это страница с материалами мастер-классов по геоинформационным системам и работе с пространственными данными для магистерской программы НИУ ВШЭ “Цифровые методы в гуманитарных науках”.

Мастер-классы предназначены для того, чтобы студенты гуманитарного направления поняли основные принципы работы с пространственными данными и основы картографирования. Материалы состоят из лекций, в который преимущественно представлены общие понятия геоинформатики, и практикума, в котором рассмотрены возможности использования настольной геоинформационной системы [QGIS](https://qgis.org/).

# Дополнительные ресурсы

Если вы захотите более подробно ознакомиться с некоторыми вопросами работы в геоинформационных системах и пространственным анализом, вы можете обратиться к материалам курсов для программы бакалавриата "Инновационные технологии в умном городе" и магистерской программы "Цифровая урбанистика" Института дизайна и урбанистики (Университет ИТМО).

Они в некоторых вопросах пересекаются с материалами, подготовленными для вас, но немного более подробны.

1.  *Балтыжакова Т.И.* **Геоинформационные системы** : сайт. 2026. — URL: <https://baltti.github.io/bachelor-gis-course/>. DOI: [10.5281/zenodo.19050322](https://doi.org/10.5281/zenodo.19050322)

2.  *Балтыжакова Т.И.* **Пространственный анализ урбанизированных территорий** : сайт. 2026. — URL: <https://baltti.github.io/spatial-analysis/>. DOI: [https://doi.org/10.5281/zenodo.20375919](https://baltti.github.io/spatial-analysis/10.5281/zenodo.20375919)

Также в качестве дополнительного ресурса рекомендую материалы Тимофея Самсонова:

> *Самсонов Т.Е.* **Основы геоинформатики: курс лекций** : сайт. 2025. — URL: https://tsamsonov.github.io/gis-course/. Дата публикации: 19.04.2026. DOI: 10.5281/zenodo.7902351

# Записи занятий

Записи занятий доступны по [ссылке](https://disk.yandex.ru/d/nLx61yV-YWFl1A).

::: callout-tip
## Обратная связь

Если вы заметили ошибку или опечатку, можете написать мне на почту tibaltyzhakova\@itmo.ru или оставить [issue](https://github.com/baltti/gis-hse/issues) в репозитории курса на GitHub.
:::
